# Generated by Django 6.0.3 on 2026-05-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="course",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
