# Generated by Django 6.0.3 on 2026-05-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="college",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="student_class",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
