# Generated by Django 6.0.3 on 2026-05-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_remove_result_date_result_chapter_stats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="profile_pics/"
            ),
        ),
    ]
